### ISSUE TITLE
Ищу программиста

### ISSUE THREAD

**Issue by vesnins** [waowl/images-project#1]
Привет! Ищу программиста. Если интересна работа, пиши на reconcept@mail.ru

**Comment by Andrew-Eronsky** [comment]
Приветствую! Ищу в офис Php разработчика (Laravel). 
Если интересно, пишите, пожалуйста! 
---
Best regards,

Andrew Eronsky
Talent acquisition dept | TravoLab
Tel.: +375 29 246 43 44
E-mail: recruiting@travo-lab.com
Skype:  live:7f2c8b8e4a0c7a37
Address: 40 Nemiga St., Minsk, Belarus
